name: ex4-secrets-and-env-vars
on: [push]

jobs:
  secret-and-env-var:
    name: secret-and-env-var
    runs-on: ubuntu-18.04
    env:
      JOB_ENV: "hello"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Secret
        run: echo "My secret is ${{ secrets.TEST_SECRET}}"
      - name: env var
        run: |
          echo "My job env var is $JOB_ENV"
          echo "My step env var is $TEST_ENV"
        env:
          TEST_ENV: "world"
